# Generated by Django 4.2.6 on 2023-11-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_list',
            name='question',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz_list',
            name='time',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
