# Generated by Django 4.2.6 on 2023-10-28 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_author_blog_bauthor_img_alter_blog_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author_blog',
            old_name='bauthor_img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='img',
            new_name='image',
        ),
    ]
