# Generated by Django 4.2.6 on 2023-10-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_rename_msg_contact_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('company_phone', models.CharField(max_length=20)),
                ('company_email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('company_fb', models.URLField(max_length=50)),
                ('company_linkdln', models.URLField(max_length=50)),
                ('company_yt', models.URLField(max_length=50)),
                ('company_x', models.URLField(max_length=50)),
                ('company_logo', models.ImageField(upload_to='compnay_logo/')),
            ],
        ),
    ]
