# Generated by Django 4.2.6 on 2023-10-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_company_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_info',
            name='google_map',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
