# Generated by Django 4.2.6 on 2023-10-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_alter_company_info_google_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=50)),
                ('company_fb', models.URLField(max_length=50, null=True)),
                ('company_linkdln', models.URLField(max_length=50, null=True)),
                ('company_yt', models.URLField(max_length=50, null=True)),
                ('img', models.ImageField(upload_to='Team_members/')),
            ],
        ),
    ]
