# Generated by Django 4.2.6 on 2023-10-27 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_team_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team_member',
            old_name='company_fb',
            new_name='person_fb',
        ),
        migrations.RenameField(
            model_name='team_member',
            old_name='company_linkdln',
            new_name='person_linkdln',
        ),
        migrations.RenameField(
            model_name='team_member',
            old_name='company_yt',
            new_name='person_yt',
        ),
    ]
