# Generated by Django 4.2.6 on 2023-10-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_newsletter_alter_team_member_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_info',
            name='quets',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
