# Generated by Django 4.2.6 on 2023-10-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_company_info_quets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_info',
            name='quets',
            field=models.TextField(max_length=300),
        ),
    ]
