# Generated by Django 4.2.6 on 2023-10-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_alter_company_info_quets'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_info',
            name='company_logo_footer',
            field=models.ImageField(default=0, upload_to='compnay_logo/'),
            preserve_default=False,
        ),
    ]
