# Generated by Django 4.2.6 on 2023-10-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_company_info_android_company_info_ios'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('youtube', models.URLField(max_length=100, null=True)),
                ('comment', models.TextField(max_length=500)),
                ('teacher_rules', models.TextField()),
                ('expert_rules', models.TextField()),
                ('education', models.TextField()),
            ],
        ),
    ]
