# Generated by Django 4.2.6 on 2023-10-31 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0015_beteacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beteacher',
            name='education',
        ),
        migrations.RemoveField(
            model_name='beteacher',
            name='expert_rules',
        ),
        migrations.RemoveField(
            model_name='beteacher',
            name='teacher_rules',
        ),
    ]
