# Generated by Django 4.2.6 on 2023-10-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0016_remove_beteacher_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beteacher',
            name='cv',
            field=models.FileField(default=0, upload_to='teacher/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beteacher',
            name='youtube',
            field=models.URLField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
