# Generated by Django 4.2.6 on 2023-10-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0017_beteacher_cv_alter_beteacher_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beteacher',
            name='cv',
            field=models.FileField(upload_to='media/teacher/'),
        ),
    ]
