# Generated by Django 4.2.6 on 2023-10-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0019_alter_beteacher_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=300),
        ),
    ]
