# Generated by Django 4.2.6 on 2023-10-31 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0020_alter_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beteacher',
            name='phone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Typical format for a mobile phone number inside Bangladesh is 01XXX NNNNNN, and +880 1XXX NNNNNN when dialed internationally.. Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Typical format for a mobile phone number inside Bangladesh is 01XXX NNNNNN, and +880 1XXX NNNNNN when dialed internationally.. Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
