# Generated by Django 4.2.6 on 2023-11-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0021_alter_beteacher_phone_alter_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/hero/')),
                ('featured_video', models.URLField()),
                ('workshop_name', models.CharField(max_length=50)),
                ('workshop_join_link', models.URLField(max_length=50)),
                ('hero_title', models.CharField(max_length=150)),
                ('hero_slogan', models.CharField(max_length=150)),
            ],
        ),
    ]
