# Generated by Django 4.2.6 on 2023-11-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0023_alter_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='hero_title',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/hero/'),
        ),
    ]
