# Generated by Django 4.2.6 on 2023-11-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0024_alter_hero_hero_title_alter_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='hero_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
