# Generated by Django 4.2.6 on 2023-11-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0025_alter_hero_hero_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='hero_title',
        ),
        migrations.AlterField(
            model_name='beteacher',
            name='cv',
            field=models.FileField(upload_to='teacher_registraion_files/'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
    ]
