# Generated by Django 4.2.6 on 2023-11-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0026_remove_hero_hero_title_alter_beteacher_cv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=50)),
                ('image', models.ImageField(default='feedback/default.png', error_messages='Upload Your Photo', upload_to='feedback/')),
                ('feedback', models.TextField(error_messages='give feedback about between 300 char', max_length=300)),
                ('published', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
