# Generated by Django 4.2.6 on 2023-11-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0027_student_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_feedback',
            name='published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
