# Generated by Django 4.2.6 on 2023-11-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0029_alter_student_feedback_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_feedback',
            name='feedback',
        ),
        migrations.AddField(
            model_name='student_feedback',
            name='feedback_text',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
