# Generated by Django 4.2.6 on 2023-11-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0030_remove_student_feedback_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_feedback',
            name='section_img',
            field=models.ImageField(blank=True, null=True, upload_to='feedback/'),
        ),
    ]
