# Generated by Django 4.2.6 on 2023-11-01 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0031_student_feedback_section_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_feedback',
            name='section_img',
        ),
    ]
