# Generated by Django 4.2.6 on 2023-11-01 16:53

from django.db import migrations, models
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0033_alter_beteacher_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_feedback',
            name='image',
            field=models.ImageField(blank=True, default='feedback/default.png', error_messages='Upload Your Photo', null=True, upload_to=lms.models.UploadToPath('feedback/')),
        ),
    ]
