# Generated by Django 4.2.6 on 2023-11-01 16:57

from django.db import migrations, models
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0034_alter_student_feedback_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_member',
            name='img',
        ),
        migrations.AddField(
            model_name='team_member',
            name='image',
            field=models.ImageField(default=0, upload_to=lms.models.UploadToPath('Team_members/')),
            preserve_default=False,
        ),
    ]
