# Generated by Django 4.2.6 on 2023-11-01 17:21

import django.core.validators
from django.db import migrations, models
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0035_remove_team_member_img_team_member_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=150)),
                ('your_email', models.EmailField(max_length=150)),
                ('your_phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Typical format for a mobile phone number inside Bangladesh is 01XXX NNNNNN, and +880 1XXX NNNNNN when dialed internationally.. Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')])),
                ('your_image', models.ImageField(blank=True, default='', null=True, upload_to=lms.models.UploadToPath('project_register/'))),
                ('project_url', models.URLField()),
                ('project_title', models.URLField()),
                ('project_Screen_short', models.ImageField(blank=True, default='', null=True, upload_to=lms.models.UploadToPath('project_register/projectss/'))),
                ('project_price', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], max_length=50)),
                ('accept', models.BooleanField()),
            ],
        ),
    ]
