# Generated by Django 4.2.6 on 2023-11-01 17:35

from django.db import migrations, models
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0036_register_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_project',
            name='project_Screen_short',
            field=models.ImageField(blank=True, default='', null=True, upload_to=lms.models.UploadToPath('project_register/')),
        ),
    ]
