# Generated by Django 4.2.6 on 2023-11-01 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0037_alter_register_project_project_screen_short'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_project',
            old_name='project_Screen_short',
            new_name='project_screen_short',
        ),
    ]
