# Generated by Django 4.2.6 on 2023-11-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0038_rename_project_screen_short_register_project_project_screen_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_project',
            name='project_language',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register_project',
            name='your_designation',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
