# Generated by Django 4.2.6 on 2023-11-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0041_alter_register_project_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_project',
            name='project_screen_short',
            field=models.ImageField(blank=True, default='', null=True, upload_to='project_register/project_ss'),
        ),
        migrations.AlterField(
            model_name='register_project',
            name='your_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='project_register/'),
        ),
    ]
