# Generated by Django 4.2.6 on 2023-11-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0044_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='event_name',
        ),
        migrations.AddField(
            model_name='gallery',
            name='event_name',
            field=models.ManyToManyField(to='lms.event'),
        ),
    ]
