# Generated by Django 4.2.6 on 2023-11-03 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0045_event_remove_gallery_event_name_gallery_event_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='event_name',
        ),
        migrations.AddField(
            model_name='gallery',
            name='event_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lms.event'),
            preserve_default=False,
        ),
    ]
