# Generated by Django 4.2.6 on 2023-11-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0046_remove_gallery_event_name_gallery_event_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answare', models.TextField()),
            ],
        ),
    ]
