# Generated by Django 4.2.6 on 2023-11-23 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('notice_title', models.CharField(max_length=255)),
                ('notice_details', models.TextField()),
                ('file_upload', models.FileField(upload_to='notice/')),
                ('notice_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notice.noticeby')),
            ],
        ),
    ]
