# Generated by Django 4.2.6 on 2023-11-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='notice_for',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
