# Generated by Django 4.2.6 on 2023-11-23 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_notice_notice_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='notice_details',
        ),
    ]
